version: "3.7"
services:
  app:
    build: .
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - db
  db:
    image: "dbafromthecold/sqlserver2012dev:sp4"
    ports: 
      - 1433:1433
    environment:
      SA_PASSWORD: "12341234"
      ACCEPT_EULA: "Y"
